/**
 * Wipe + seed MongoDB demo data for Roomzy — 52 Varanasi, India Hotels.
 *
 * Usage: npm run seed
 * Requires MONGODB_CONNECTION_STRING in .env
 */
import "dotenv/config";
import mongoose from "mongoose";
import User from "../models/user";
import Hotel from "../models/hotel";
import Booking from "../models/booking";
import Review from "../models/review";
import Analytics from "../models/analytics";

const IMAGES = [
  "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
  "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800",
  "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800",
  "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800",
  "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800",
  "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800",
  "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800",
  "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800",
  "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800",
  "https://images.unsplash.com/photo-1591088398332-8a7791972843?w=800",
  "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=800",
  "https://images.unsplash.com/photo-1568495248636-6432b97bd949?w=800",
];

const daysFromNow = (n: number) => {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d;
};

const daysAgo = (n: number) => daysFromNow(-n);

// 52 Authentic & Realistic Varanasi Hotels
const varanasiHotelsData = [
  {
    name: "BrijRama Palace — Heritage Hotel on Darbhanga Ghat",
    description: "An 18th-century royal heritage palace standing on the sacred banks of the Ganges. Features private bajra boat rides, sitar concerts, and classical Banarasi dining overlooking the river.",
    type: ["Heritage", "Luxury", "Riverside"],
    facilities: ["Free WiFi", "Ganga View", "Pure Veg Restaurant", "Boat Ride Desk", "Spa & Wellness", "Airport Shuttle"],
    pricePerNight: 16500,
    starRating: 5,
    street: "Darbhanga Ghat, Dashashwamedh",
    zipCode: "221001",
    lat: 25.3056,
    lng: 83.0102,
    phone: "+91 542 245 1234",
  },
  {
    name: "Taj Ganges Varanasi, Cantonment",
    description: "Spread over 40 acres of lush green gardens in the serene Cantonment area. Offers premier luxury, international dining at Chowk, and signature Jiva Spa treatments.",
    type: ["Luxury", "Resort", "Business"],
    facilities: ["Free WiFi", "Swimming Pool", "Spa & Massage", "Fitness Center", "Fine Dining", "Parking"],
    pricePerNight: 12800,
    starRating: 5,
    street: "Nadesar Palace Grounds, Cantt",
    zipCode: "221002",
    lat: 25.3374,
    lng: 82.9739,
    phone: "+91 542 666 0001",
  },
  {
    name: "Amritara Suryauday Haveli, Shivala Ghat",
    description: "A meticulously restored 20th-century haveli built by the royal family of Nepal. Enjoy morning yoga on the rooftop and panoramic sunrise views over the Ganga.",
    type: ["Heritage", "Boutique", "Riverside"],
    facilities: ["Free WiFi", "Rooftop Aarti View", "Riverfront Dining", "Air Conditioning", "Room Service"],
    pricePerNight: 9400,
    starRating: 4,
    street: "B-4/25 Shivala Ghat",
    zipCode: "221001",
    lat: 25.2988,
    lng: 83.0062,
    phone: "+91 542 227 5000",
  },
  {
    name: "Radisson Hotel Varanasi",
    description: "Modern 5-star hotel in the business hub of Cantonment. Features stylish rooms, outdoor swimming pool, EastWest cafe, and luxury banquet facilities.",
    type: ["Luxury", "Business", "Modern"],
    facilities: ["Free WiFi", "Swimming Pool", "Bar / Lounge", "Valet Parking", "Fitness Center", "Airport Pickup"],
    pricePerNight: 7500,
    starRating: 5,
    street: "RH Towers, Main Mall Road, Cantt",
    zipCode: "221002",
    lat: 25.3421,
    lng: 82.9798,
    phone: "+91 542 250 1515",
  },
  {
    name: "Hotel Ganga View & Suites, Assi Ghat",
    description: "Charming riverside hotel located right by Assi Ghat. Ideal for morning Ganga Aarti, music festivals, Subah-e-Banaras, and bohemian riverside cafes.",
    type: ["Riverside", "Boutique", "Family"],
    facilities: ["Free WiFi", "Rooftop Cafe", "Ganga View Balcony", "Air Conditioning", "Doctor on Call"],
    pricePerNight: 4200,
    starRating: 4,
    street: "Assi Ghat Road, Near Tulsi Ghat",
    zipCode: "221005",
    lat: 25.2882,
    lng: 83.0033,
    phone: "+91 542 231 6688",
  },
  {
    name: "Kashi Vishwanath Residency, Godowlia",
    description: "Just 250 meters from Kashi Vishwanath Dham Corridor and Dashashwamedh Ghat. Features pure vegetarian sattvic restaurant and VIP temple darshan assistance.",
    type: ["Pilgrimage", "Budget", "Family"],
    facilities: ["Free WiFi", "Veg Restaurant", "Temple Darshan Desk", "Elevator", "24/7 Hot Water"],
    pricePerNight: 3200,
    starRating: 4,
    street: "D-14/19 Godowlia Crossing",
    zipCode: "221001",
    lat: 25.3092,
    lng: 83.0076,
    phone: "+91 542 240 3344",
  },
  {
    name: "Ramada Plaza by Wyndham JHV Varanasi",
    description: "Upscale 5-star hotel with landscaped gardens, tennis courts, multiple specialty restaurants, and a state-of-the-art spa center.",
    type: ["Luxury", "Resort", "Business"],
    facilities: ["Free WiFi", "Swimming Pool", "Tennis Court", "Spa", "Free Parking", "Multi-Cuisine"],
    pricePerNight: 8900,
    starRating: 5,
    street: "The Mall, Cantonment",
    zipCode: "221002",
    lat: 25.3389,
    lng: 82.9812,
    phone: "+91 542 251 0000",
  },
  {
    name: "Tree of Life Resort & Spa, Varanasi",
    description: "Tranquil luxury resort surrounded by sacred groves on the outskirts of Varanasi. Handcrafted architecture reflecting ancient Buddhist and Vedic heritage.",
    type: ["Resort", "Luxury", "Wellness"],
    facilities: ["Free WiFi", "Private Villas", "Ayurvedic Spa", "Organic Dining", "Swimming Pool"],
    pricePerNight: 11500,
    starRating: 5,
    street: "Seer Goverdhanpur, Near BHU",
    zipCode: "221011",
    lat: 25.2654,
    lng: 82.9845,
    phone: "+91 542 289 7788",
  },
  {
    name: "The Clarks Varanasi, Cantt",
    description: "One of India's oldest heritage luxury hotels, established in 1835. Beautiful colonial architecture, historic banquet halls, and lush garden lawns.",
    type: ["Heritage", "Luxury", "Business"],
    facilities: ["Free WiFi", "Swimming Pool", "Colonial Bar", "Travel Desk", "Coffee Shop"],
    pricePerNight: 6800,
    starRating: 5,
    street: "The Mall, Cantt",
    zipCode: "221002",
    lat: 25.3367,
    lng: 82.9774,
    phone: "+91 542 250 1011",
  },
  {
    name: "Palace on Ganges Heritage Hotel, Assi",
    description: "Themed rooms showcasing cultural regions of India along the sacred river. Rooftop terrace with unmatched views of the morning Ganga Aarti.",
    type: ["Heritage", "Riverside", "Boutique"],
    facilities: ["Free WiFi", "Rooftop Restaurant", "Cultural Shows", "Air Conditioning", "Laundry"],
    pricePerNight: 5100,
    starRating: 4,
    street: "B-1/158 Assi Ghat",
    zipCode: "221005",
    lat: 25.2895,
    lng: 83.0041,
    phone: "+91 542 231 4304",
  },
  {
    name: "Hotel Surya, Kaiser Palace, Mall Road",
    description: "Grand heritage property originally built in 1810 for the King of Nepal. Features the famous Canton Royale restaurant and Shanti Spa.",
    type: ["Heritage", "Boutique", "Family"],
    facilities: ["Free WiFi", "Swimming Pool", "Spa & Wellness", "Garden Cafe", "Bar"],
    pricePerNight: 4800,
    starRating: 4,
    street: "S-20/51-A, The Mall Road, Cantt",
    zipCode: "221002",
    lat: 25.3341,
    lng: 82.9822,
    phone: "+91 542 250 8466",
  },
  {
    name: "Zostel Varanasi, Dashashwamedh",
    description: "Vibrant and social backpacker hostel with private suites and dorms, colorful murals, rooftop cafe, and walking tours of hidden ghats.",
    type: ["Budget", "Boutique", "Youth"],
    facilities: ["Free WiFi", "Rooftop Common Room", "Cafe", "Lockers", "Tour Guide Desk"],
    pricePerNight: 1600,
    starRating: 3,
    street: "D-58/12-A-7, Luxa Road",
    zipCode: "221001",
    lat: 25.3088,
    lng: 83.0012,
    phone: "+91 542 245 9900",
  },
  {
    name: "GoStops Varanasi, Assi Ghat",
    description: "Modern youth hostel and boutique budget rooms located 300m from Assi Ghat. Rooftop seating, board games, community events, and superfast WiFi.",
    type: ["Budget", "Boutique", "Youth"],
    facilities: ["Free WiFi", "Air Conditioning", "Game Zone", "Rooftop Terrace", "Luggage Storage"],
    pricePerNight: 1450,
    starRating: 3,
    street: "B-1/128-2, Dumraon Bagh, Assi",
    zipCode: "221005",
    lat: 25.2875,
    lng: 83.0028,
    phone: "+91 542 231 9911",
  },
  {
    name: "Gautam Buddha Resort, Sarnath",
    description: "Peaceful resort near the historic Sarnath Deer Park and Dhamek Stupa. Lush landscaped greenery, meditation courtyards, and pure vegetarian food.",
    type: ["Resort", "Pilgrimage", "Peaceful"],
    facilities: ["Free WiFi", "Meditation Garden", "Veg Restaurant", "Parking", "Sightseeing Bus"],
    pricePerNight: 3600,
    starRating: 4,
    street: "Near Dhamek Stupa, Sarnath",
    zipCode: "221007",
    lat: 25.3812,
    lng: 83.0234,
    phone: "+91 542 259 5500",
  },
  {
    name: "Hotel Swastik Inn, Sigra",
    description: "Contemporary mid-range hotel situated in the central shopping and commercial district of Sigra. Easy commute to Varanasi Cantt station.",
    type: ["Business", "Budget", "Family"],
    facilities: ["Free WiFi", "Restaurant", "Conference Hall", "Room Service", "Power Backup"],
    pricePerNight: 2400,
    starRating: 3,
    street: "C-27/274, Maldahiya, Sigra",
    zipCode: "221002",
    lat: 25.3211,
    lng: 82.9867,
    phone: "+91 542 222 3311",
  },
  {
    name: "Hotel Alka, Mir Ghat (Ganga Front)",
    description: "Spectacular riverfront hotel located directly on Mir Ghat with private balconies looking straight at the Ganga Aarti boats and sunrise.",
    type: ["Riverside", "Budget", "Heritage"],
    facilities: ["Free WiFi", "Ganga View Balcony", "Rooftop Restaurant", "Boat Booking", "Yoga Space"],
    pricePerNight: 2800,
    starRating: 3,
    street: "D-3/23 Mir Ghat",
    zipCode: "221001",
    lat: 25.3075,
    lng: 83.0118,
    phone: "+91 542 239 8445",
  },
  {
    name: "Rivatas by Ideal, Cantt",
    description: "Sophisticated boutique luxury hotel with outdoor pool, Ocean multicuisine restaurant, and full conference amenities in Cantonment.",
    type: ["Luxury", "Business", "Modern"],
    facilities: ["Free WiFi", "Swimming Pool", "Bar & Grill", "Gym", "Banquet Hall", "Valet"],
    pricePerNight: 6200,
    starRating: 4,
    street: "Mall Road, Cantonment",
    zipCode: "221002",
    lat: 25.3415,
    lng: 82.9782,
    phone: "+91 542 250 2020",
  },
  {
    name: "Hotel Hindustan International (HHI) Varanasi",
    description: "Premium city-center hotel featuring spacious deluxe rooms, poolside lounge, Aangan North Indian cuisine, and high-speed business amenities.",
    type: ["Luxury", "Business", "Family"],
    facilities: ["Free WiFi", "Poolside Lounge", "Gymnasium", "Free Parking", "Airport Shuttle"],
    pricePerNight: 5800,
    starRating: 4,
    street: "C-21/1-A, Maldahiya",
    zipCode: "221002",
    lat: 25.3255,
    lng: 82.9888,
    phone: "+91 542 222 1414",
  },
  {
    name: "Hotel Tridev, Golghar",
    description: "Modern upscale hotel near Visheshwarganj and Kashi Vishwanath Dham. Famous for pure vegetarian Banarasi delicacies and luxurious banqueting.",
    type: ["Business", "Pilgrimage", "Family"],
    facilities: ["Free WiFi", "Pure Veg Restaurant", "Doctor on Call", "Travel Desk", "Elevator"],
    pricePerNight: 3900,
    starRating: 4,
    street: "A-2/139 Golghar, Maidagin",
    zipCode: "221001",
    lat: 25.3188,
    lng: 83.0125,
    phone: "+91 542 241 8800",
  },
  {
    name: "Hotel Meraden Grand, Cantt",
    description: "Elegant 4-star property with international standards, Golden Dragon Chinese restaurant, and well-appointed executive suites.",
    type: ["Business", "Luxury", "Family"],
    facilities: ["Free WiFi", "Specialty Restaurant", "Cocktail Lounge", "Fitness Center", "Parking"],
    pricePerNight: 4600,
    starRating: 4,
    street: "53st, Patel Nagar, Cantt",
    zipCode: "221002",
    lat: 25.3362,
    lng: 82.9745,
    phone: "+91 542 250 4444",
  },
  {
    name: "Hotel Diamond, Bhelupur",
    description: "Established 4-star hotel in the tranquil residential hub of Bhelupur. Features the Diamond Veg banquet and easy access to Sankat Mochan Temple.",
    type: ["Heritage", "Family", "Business"],
    facilities: ["Free WiFi", "Vegetarian Dining", "Event Lawn", "Free Parking", "Room Service"],
    pricePerNight: 3500,
    starRating: 4,
    street: "Bhelupur Crossing, Varanasi",
    zipCode: "221010",
    lat: 25.2995,
    lng: 82.9972,
    phone: "+91 542 227 6221",
  },
  {
    name: "Hotel City Inn, Varanasi Cantt",
    description: "Conveniently located 100 meters from Varanasi Junction Railway Station. Ideal for travelers wanting quick train access and comfortable modern stays.",
    type: ["Budget", "Transit", "Business"],
    facilities: ["Free WiFi", "24/7 Front Desk", "Restaurant", "Elevator", "Luggage Storage"],
    pricePerNight: 2100,
    starRating: 3,
    street: "Station Road, Cantt",
    zipCode: "221002",
    lat: 25.3312,
    lng: 82.9855,
    phone: "+91 542 220 5050",
  },
  {
    name: "Namaste Banaras Boutique Stay, Ravindrapuri",
    description: "An artistic boutique hotel celebrating the rich silk weaving, classical thumri music, and culinary heritage of Banaras with bespoke rooms.",
    type: ["Boutique", "Heritage", "Art"],
    facilities: ["Free WiFi", "Art Gallery Lounge", "Banarasi Breakfast", "AC", "Rooftop Yoga"],
    pricePerNight: 3800,
    starRating: 4,
    street: "Lane 3, Ravindrapuri Extension",
    zipCode: "221005",
    lat: 25.2912,
    lng: 82.9945,
    phone: "+91 542 231 1009",
  },
  {
    name: "Hotel Temple on Ganges, Assi Ghat",
    description: "Traditional pilgrim lodge with rooftop restaurant overlooking the southern ghats. Walking distance to BHU, Tulsi Manas Temple, and Sankat Mochan.",
    type: ["Riverside", "Budget", "Pilgrimage"],
    facilities: ["Free WiFi", "Rooftop Restaurant", "Yoga Classes", "Travel Desk", "Hot Water"],
    pricePerNight: 2200,
    starRating: 3,
    street: "Gurudham Colony, Assi Ghat",
    zipCode: "221005",
    lat: 25.2867,
    lng: 83.0039,
    phone: "+91 542 231 7733",
  },
  {
    name: "Hotel Grapevine Varanasi, Durgakund",
    description: "Comfortable hotel situated right across from the historic Durga Kund Temple. Features contemporary rooms, rooftop cafe, and family suites.",
    type: ["Budget", "Family", "Pilgrimage"],
    facilities: ["Free WiFi", "Rooftop Cafe", "Family Suites", "Air Conditioning", "Lift"],
    pricePerNight: 2600,
    starRating: 3,
    street: "Durgakund Road, Anandbagh",
    zipCode: "221005",
    lat: 25.2922,
    lng: 82.9992,
    phone: "+91 542 231 4455",
  },
  {
    name: "Hotel Banaras Haveli, Shivala",
    description: "Classic Banarasi haveli with carved archways and internal courtyard. Offers tranquil stay experience a short stroll from Harishchandra Ghat.",
    type: ["Heritage", "Boutique", "Riverside"],
    facilities: ["Free WiFi", "Courtyard Dining", "Ganga View", "AC Rooms", "Boat Hire"],
    pricePerNight: 3700,
    starRating: 4,
    street: "B-3/209 Shivala, Varanasi",
    zipCode: "221001",
    lat: 25.2974,
    lng: 83.0071,
    phone: "+91 542 227 8899",
  },
  {
    name: "SaffronStays Kashi Vista Riverside Villa",
    description: "Private luxury boutique villa with direct views of the Ganges. Features authentic marble interiors, curated Banarasi chef meals, and private terrace.",
    type: ["Luxury", "Boutique", "Riverside"],
    facilities: ["Free WiFi", "Private Chef", "Ganga Panorama", "Butler Service", "Terrace Lounge"],
    pricePerNight: 14200,
    starRating: 5,
    street: "Kedar Ghat Promenade",
    zipCode: "221001",
    lat: 25.3012,
    lng: 83.0089,
    phone: "+91 542 245 7711",
  },
  {
    name: "The Fern Residency, Varanasi",
    description: "Eco-friendly business and leisure hotel by Fern Hotels. Offering modern sustainable luxury, multi-cuisine restaurant, and rooftop pool.",
    type: ["Modern", "Business", "Luxury"],
    facilities: ["Free WiFi", "Rooftop Pool", "Eco Friendly", "Restaurant", "Gym"],
    pricePerNight: 5400,
    starRating: 4,
    street: "Hukulganj, Pandeypur Road",
    zipCode: "221002",
    lat: 25.3444,
    lng: 82.9912,
    phone: "+91 542 258 0000",
  },
  {
    name: "Hotel Runway Inn, Babatpur Airport Road",
    description: "Modern luxury hotel located 5 minutes from Lal Bahadur Shastri International Airport (VNS). Ideal for transit passengers and air crew.",
    type: ["Airport", "Transit", "Modern"],
    facilities: ["Free WiFi", "Airport Shuttle", "24/7 Dining", "Express Check-in", "Soundproof Rooms"],
    pricePerNight: 3400,
    starRating: 4,
    street: "NH-56, Babatpur Airport Road",
    zipCode: "221006",
    lat: 25.4489,
    lng: 82.8574,
    phone: "+91 542 262 2222",
  },
  {
    name: "Scindhia Guest House & Riverside Cafe",
    description: "Iconic riverside guest house situated directly on Scindhia Ghat. Offers authentic backpacker warmth and unparalleled river views from its terrace.",
    type: ["Budget", "Riverside", "Heritage"],
    facilities: ["Free WiFi", "Riverfront Terrace", "Cafe", "Yoga Lessons", "Boat Excursions"],
    pricePerNight: 1800,
    starRating: 3,
    street: "Scindhia Ghat, Manikarnika Area",
    zipCode: "221001",
    lat: 25.3114,
    lng: 83.0142,
    phone: "+91 542 239 0012",
  },
  {
    name: "Hotel Madhuvan Heritage, Chetganj",
    description: "Welcoming heritage-style hotel in the bustling traditional market area of Chetganj. Easy access to Banarasi saree weaver colonies.",
    type: ["Heritage", "Budget", "Family"],
    facilities: ["Free WiFi", "Saree Shopping Tours", "Vegetarian Kitchen", "AC", "Power Backup"],
    pricePerNight: 2300,
    starRating: 3,
    street: "Chetganj Crossing, Varanasi",
    zipCode: "221001",
    lat: 25.3167,
    lng: 82.9984,
    phone: "+91 542 241 1212",
  },
  {
    name: "Kashi Stay & Suites, Lanka BHU",
    description: "Popular hotel near Banaras Hindu University main gate and Sir Sunderlal Hospital. Clean, modern amenities favored by academic and family visitors.",
    type: ["Budget", "Modern", "Family"],
    facilities: ["Free WiFi", "In-house Cafe", "Study Desks", "Elevator", "Laundry"],
    pricePerNight: 2200,
    starRating: 3,
    street: "Lanka Crossing, Near BHU Gate",
    zipCode: "221005",
    lat: 25.2789,
    lng: 82.9988,
    phone: "+91 542 236 6777",
  },
  {
    name: "Hotel Swastik Inn, Pandeypur",
    description: "Peaceful residential hotel in North Varanasi. Offers spacious deluxe rooms, quiet surroundings, and swift connectivity to Ring Road.",
    type: ["Budget", "Family", "Transit"],
    facilities: ["Free WiFi", "Parking", "Room Service", "AC", "Hot Water"],
    pricePerNight: 1900,
    starRating: 3,
    street: "Pandeypur Chauraha, Azamgarh Road",
    zipCode: "221002",
    lat: 25.3512,
    lng: 82.9982,
    phone: "+91 542 258 4400",
  },
  {
    name: "Ganges Grand Hotel, Godowlia Crossing",
    description: "Premium commercial hotel situated right at Godowlia Chowk. Step out directly into the bustling street food lanes and Aarti markets.",
    type: ["Modern", "Pilgrimage", "Business"],
    facilities: ["Free WiFi", "Roof Garden Restaurant", "Banquet Hall", "Elevator", "Doctor on Call"],
    pricePerNight: 4100,
    starRating: 4,
    street: "D-5/64 Godowlia Crossing",
    zipCode: "221001",
    lat: 25.3098,
    lng: 83.0068,
    phone: "+91 542 245 4488",
  },
  {
    name: "The Royal Banaras Residency, Shivpur",
    description: "Grand banquet resort with landscaped green lawns, opulent bridal suites, and peaceful rooms on the VIP highway.",
    type: ["Resort", "Luxury", "Events"],
    facilities: ["Free WiFi", "Party Lawns", "Multi-Cuisine", "Swimming Pool", "Parking"],
    pricePerNight: 5500,
    starRating: 4,
    street: "Shivpur Bypass, Varanasi",
    zipCode: "221003",
    lat: 25.3678,
    lng: 82.9612,
    phone: "+91 542 228 1111",
  },
  {
    name: "Aura Banaras Boutique Hotel, Ravindrapuri",
    description: "Trendy modern boutique stay featuring artisanal terracotta artwork, specialty coffee shop, and curated silk shopping experiences.",
    type: ["Boutique", "Modern", "Art"],
    facilities: ["Free WiFi", "Artisan Coffee Bar", "AC", "Laundry", "Airport Shuttle"],
    pricePerNight: 3900,
    starRating: 4,
    street: "Ravindrapuri Road, Near IP Mall",
    zipCode: "221005",
    lat: 25.2934,
    lng: 82.9922,
    phone: "+91 542 231 8800",
  },
  {
    name: "Om Vilas Benares Luxury Camp & Resort",
    description: "Exclusive luxury glamping and tented resort with royal Mughal tents, bonfire evenings, classical kathak dance, and fine dining.",
    type: ["Resort", "Luxury", "Glamping"],
    facilities: ["Free WiFi", "Luxury Tents", "Cultural Evenings", "Swimming Pool", "Spa"],
    pricePerNight: 10500,
    starRating: 5,
    street: "Sultanpur, Chunar Road",
    zipCode: "221011",
    lat: 25.2412,
    lng: 82.9512,
    phone: "+91 542 277 4411",
  },
  {
    name: "Hotel Temple View, Manikarnika Lane",
    description: "Historic guest house in the ancient gallis of Kashi. Experience the raw spiritual pulse of the oldest living city right at your doorstep.",
    type: ["Budget", "Heritage", "Pilgrimage"],
    facilities: ["Free WiFi", "Rooftop Ganga View", "Authentic Chai Stall", "24/7 Desk"],
    pricePerNight: 1500,
    starRating: 3,
    street: "CK 8/182 Manikarnika Ghat Lane",
    zipCode: "221001",
    lat: 25.3108,
    lng: 83.0135,
    phone: "+91 542 240 1199",
  },
  {
    name: "Kashi Vedic Village Resort, Ramnagar",
    description: "Riverside wellness sanctuary opposite Ramnagar Fort. Offers Panchakarma Ayurvedic treatments, satvik dining, and morning river dips.",
    type: ["Resort", "Wellness", "Riverside"],
    facilities: ["Free WiFi", "Ayurvedic Hospital", "Yoga Shala", "Organic Garden", "Boat Transfer"],
    pricePerNight: 6900,
    starRating: 4,
    street: "Fort Road, Ramnagar",
    zipCode: "221008",
    lat: 25.2712,
    lng: 83.0289,
    phone: "+91 542 267 9900",
  },
  {
    name: "Hotel Swarn Ganga, Dashashwamedh",
    description: "Centrally located hotel within 3 minutes walk to the evening Ganga Aarti and Vishwanath Temple gate 4.",
    type: ["Budget", "Pilgrimage", "Family"],
    facilities: ["Free WiFi", "Elevator", "Pure Veg Meals", "AC Rooms", "Darshan Assistance"],
    pricePerNight: 2900,
    starRating: 3,
    street: "Dashashwamedh Ghat Road",
    zipCode: "221001",
    lat: 25.3081,
    lng: 83.0094,
    phone: "+91 542 245 6677",
  },
  {
    name: "Shivay Grand Luxury Suites, Mahmoorganj",
    description: "Premium business hotel with contemporary marble suites, fine dining restaurant, and proximity to the Varanasi financial district.",
    type: ["Luxury", "Business", "Modern"],
    facilities: ["Free WiFi", "Executive Lounge", "Fine Dining", "Gym", "Valet Parking"],
    pricePerNight: 4900,
    starRating: 4,
    street: "D-59/103 Mahmoorganj",
    zipCode: "221010",
    lat: 25.3145,
    lng: 82.9788,
    phone: "+91 542 222 7700",
  },
  {
    name: "Banaras Ghats Riverside Retreat, Panchganga",
    description: "Charming traditional stone mansion overlooking Panchganga Ghat and Alamgir Mosque. Serene, peaceful, and rich in history.",
    type: ["Heritage", "Riverside", "Boutique"],
    facilities: ["Free WiFi", "River Terrace", "Home Cooked Meals", "Yoga Mat", "Library"],
    pricePerNight: 3300,
    starRating: 3,
    street: "K-22/11 Panchganga Ghat",
    zipCode: "221001",
    lat: 25.3155,
    lng: 83.0177,
    phone: "+91 542 243 0088",
  },
  {
    name: "Hotel Heritage Inn, Luxa Road",
    description: "Family-friendly hotel with spacious interconnected rooms, pure vegetarian thali restaurant, and easy parking facilities.",
    type: ["Budget", "Family", "Modern"],
    facilities: ["Free WiFi", "Veg Thali Restaurant", "Parking", "Elevator", "AC"],
    pricePerNight: 2700,
    starRating: 3,
    street: "Luxa Road, Near PDR Mall",
    zipCode: "221001",
    lat: 25.3072,
    lng: 83.0004,
    phone: "+91 542 245 1100",
  },
  {
    name: "Marigold Riverside Villa, Rajghat",
    description: "Quiet riverside boutique villa located near Malviya Bridge and Rajghat. Offers tranquil garden views and boat tours to bird-watching spots.",
    type: ["Riverside", "Boutique", "Peaceful"],
    facilities: ["Free WiFi", "Lawn Garden", "River View", "Boat Tour", "Kitchenette"],
    pricePerNight: 4300,
    starRating: 4,
    street: "Rajghat Fort Area",
    zipCode: "221001",
    lat: 25.3289,
    lng: 83.0312,
    phone: "+91 542 244 5566",
  },
  {
    name: "Hotel Kashi Pride, Cantt Station",
    description: "Budget business hotel just 2 minutes from Varanasi Railway Station platforms. Modern showers, clean linen, and express breakfast.",
    type: ["Budget", "Transit", "Modern"],
    facilities: ["Free WiFi", "24/7 Check-in", "Express Breakfast", "AC", "Elevator"],
    pricePerNight: 1950,
    starRating: 3,
    street: "Englishia Line, Cantt",
    zipCode: "221002",
    lat: 25.3301,
    lng: 82.9839,
    phone: "+91 542 220 1199",
  },
  {
    name: "Sarnath Peace Pagoda Retreat & Spa",
    description: "Peaceful Buddhist retreat center near Sarnath Thai Temple. Surrounded by lotus ponds, offering mindfulness sessions and vegan cuisine.",
    type: ["Resort", "Peaceful", "Wellness"],
    facilities: ["Free WiFi", "Lotus Pond Garden", "Vegan Restaurant", "Meditation Hall", "Spa"],
    pricePerNight: 3800,
    starRating: 4,
    street: "Thai Temple Road, Sarnath",
    zipCode: "221007",
    lat: 25.3788,
    lng: 83.0255,
    phone: "+91 542 259 8811",
  },
  {
    name: "Hotel Swarna Kashi, Kedareshwar",
    description: "Cozy heritage stay near Kedar Ghat. Famous for authentic South Indian vegetarian canteen and morning temple pujas.",
    type: ["Pilgrimage", "Budget", "Family"],
    facilities: ["Free WiFi", "South Indian Canteen", "AC Rooms", "Travel Desk", "Hot Water"],
    pricePerNight: 2100,
    starRating: 3,
    street: "Kedar Ghat Galli, Sonarpura",
    zipCode: "221001",
    lat: 25.3008,
    lng: 83.0075,
    phone: "+91 542 245 3300",
  },
  {
    name: "Hotel Grand Kashi, Rathyatra Crossing",
    description: "Centrally located commercial property with spacious banquet halls, rooftop barbecue, and fast access to Sigra and Godowlia.",
    type: ["Business", "Modern", "Family"],
    facilities: ["Free WiFi", "Rooftop Grill", "Banquet Hall", "Parking", "AC"],
    pricePerNight: 3300,
    starRating: 4,
    street: "Rathyatra Crossing, Mahmoorganj Road",
    zipCode: "221010",
    lat: 25.3122,
    lng: 82.9845,
    phone: "+91 542 222 9900",
  },
  {
    name: "Ganga Kripa Heritage Stay, Tulsi Ghat",
    description: "Centuries-old family haveli right next to Tulsi Ghat where Goswami Tulsidas penned Ramcharitmanas. Atmospheric and deeply cultural.",
    type: ["Heritage", "Riverside", "Pilgrimage"],
    facilities: ["Free WiFi", "Ganga View Roof", "Cultural Library", "Satvik Food", "AC"],
    pricePerNight: 3100,
    starRating: 3,
    street: "B-2/18 Tulsi Ghat",
    zipCode: "221005",
    lat: 25.2905,
    lng: 83.0048,
    phone: "+91 542 231 0022",
  },
  {
    name: "Hotel Radiant Palace, Shivpur",
    description: "Modern luxury hotel offering grand ballrooms, swimming pool, luxury suites, and airport transit convenience.",
    type: ["Luxury", "Events", "Modern"],
    facilities: ["Free WiFi", "Swimming Pool", "Grand Ballroom", "Multi-Cuisine", "Parking"],
    pricePerNight: 5200,
    starRating: 4,
    street: "Grand Trunk Road, Shivpur",
    zipCode: "221003",
    lat: 25.3645,
    lng: 82.9688,
    phone: "+91 542 228 3344",
  },
  {
    name: "Hotel Shanti Grand, Lanka",
    description: "Modern budget accommodation near BHU gate. Clean rooms, high speed internet, and friendly assistance for temple visits.",
    type: ["Budget", "Family", "Modern"],
    facilities: ["Free WiFi", "Room Service", "AC", "Elevator", "Power Backup"],
    pricePerNight: 1850,
    starRating: 3,
    street: "BHU Road, Lanka",
    zipCode: "221005",
    lat: 25.2798,
    lng: 82.9975,
    phone: "+91 542 236 1122",
  },
  {
    name: "Kashi Moksha Heritage Haveli, Manikarnika",
    description: "Spiritual residence perched right above the ancient ghats. Unrivaled cultural immersion for scholars, writers, and pilgrims seeking the heart of Varanasi.",
    type: ["Heritage", "Riverside", "Pilgrimage"],
    facilities: ["Free WiFi", "Rooftop Meditation", "Ganga Aarti Sight", "Library", "Hot Water"],
    pricePerNight: 2600,
    starRating: 3,
    street: "CK 9/45 Manikarnika Ghat",
    zipCode: "221001",
    lat: 25.3119,
    lng: 83.0139,
    phone: "+91 542 240 8822",
  },
];

async function seed() {
  const uri = process.env.MONGODB_CONNECTION_STRING;
  if (!uri) {
    console.error("Missing MONGODB_CONNECTION_STRING");
    process.exit(1);
  }

  const wantsTls =
    uri.includes("mongodb+srv://") ||
    /[?&]tls=true/i.test(uri) ||
    /[?&]ssl=true/i.test(uri);

  await mongoose.connect(uri, {
    ...(wantsTls
      ? { tls: true, tlsAllowInvalidCertificates: false }
      : {}),
  });
  console.log("Connected to MongoDB Atlas. Wiping demo collections…");

  await Promise.all([
    Review.deleteMany({}),
    Booking.deleteMany({}),
    Hotel.deleteMany({}),
    Analytics.deleteMany({}),
    User.deleteMany({}),
  ]);

  console.log("Seeding demo users (Admin, Owner, Guest)…");
  const admin = await new User({
    email: "test@user.com",
    password: "12345678",
    firstName: "Test",
    lastName: "Admin",
    image: "https://i.pravatar.cc/150?u=admin",
    role: "admin",
    phone: "+91 98765 00001",
    address: {
      street: "Nadesar Palace Grounds",
      city: "Varanasi",
      state: "Uttar Pradesh",
      country: "India",
      zipCode: "221002",
    },
    preferences: {
      preferredDestinations: ["Varanasi", "Sarnath", "Ramnagar"],
      preferredHotelTypes: ["Heritage", "Luxury", "Riverside"],
      budgetRange: { min: 2000, max: 20000 },
    },
    totalBookings: 0,
    totalSpent: 0,
    lastLogin: daysAgo(0),
    emailVerified: true,
    isActive: true,
  }).save();

  const owner = await new User({
    email: "owner@hotel.com",
    password: "12345678",
    firstName: "Hotel",
    lastName: "Owner",
    image: "https://i.pravatar.cc/150?u=owner",
    role: "hotel_owner",
    phone: "+91 98765 00002",
    address: {
      street: "Assi Ghat Promenade",
      city: "Varanasi",
      state: "Uttar Pradesh",
      country: "India",
      zipCode: "221005",
    },
    preferences: {
      preferredDestinations: ["Varanasi", "Prayagraj", "Ayodhya"],
      preferredHotelTypes: ["Heritage", "Boutique"],
      budgetRange: { min: 3000, max: 15000 },
    },
    totalBookings: 0,
    totalSpent: 0,
    lastLogin: daysAgo(1),
    emailVerified: true,
    isActive: true,
  }).save();

  const guest = await new User({
    email: "guest@user.com",
    password: "12345678",
    firstName: "Guest",
    lastName: "Traveler",
    image: "https://i.pravatar.cc/150?u=guest",
    role: "user",
    phone: "+91 98765 43210",
    address: {
      street: "Godowlia Crossing",
      city: "Varanasi",
      state: "Uttar Pradesh",
      country: "India",
      zipCode: "221001",
    },
    preferences: {
      preferredDestinations: ["Varanasi", "Sarnath"],
      preferredHotelTypes: ["Riverside", "Budget", "Heritage"],
      budgetRange: { min: 1500, max: 8000 },
    },
    totalBookings: 0,
    totalSpent: 0,
    lastLogin: daysAgo(2),
    emailVerified: true,
    isActive: true,
  }).save();

  console.log(`Seeding ${varanasiHotelsData.length} Varanasi hotels…`);
  const savedHotels = [];

  for (let i = 0; i < varanasiHotelsData.length; i++) {
    const h = varanasiHotelsData[i];
    const img1 = IMAGES[i % IMAGES.length];
    const img2 = IMAGES[(i + 3) % IMAGES.length];
    const img3 = IMAGES[(i + 6) % IMAGES.length];

    const newHotel = await new Hotel({
      userId: owner.id,
      name: h.name,
      city: "Varanasi",
      country: "India",
      description: h.description,
      type: h.type,
      adultCount: 2,
      childCount: 1,
      facilities: h.facilities,
      pricePerNight: h.pricePerNight,
      starRating: h.starRating,
      imageUrls: [img1, img2, img3],
      lastUpdated: new Date(),
      location: {
        latitude: h.lat,
        longitude: h.lng,
        address: {
          street: h.street,
          city: "Varanasi",
          state: "Uttar Pradesh",
          country: "India",
          zipCode: h.zipCode,
        },
      },
      contact: {
        phone: h.phone,
        email: `stay@${h.name.toLowerCase().replace(/[^a-z0-9]/g, "").slice(0, 15)}.in`,
        website: `https://${h.name.toLowerCase().replace(/[^a-z0-9]/g, "").slice(0, 15)}.in`,
      },
      policies: {
        checkInTime: "14:00",
        checkOutTime: "11:00",
        cancellationPolicy: "Free cancellation up to 24 hours before check-in",
        petPolicy: "Pets allowed on request in select rooms",
        smokingPolicy: "100% Non-smoking indoor rooms",
      },
      averageRating: Math.round((4.0 + (i % 10) * 0.1) * 10) / 10,
      reviewCount: 15 + (i * 7) % 60,
      totalBookings: 8 + (i * 3) % 25,
      totalRevenue: h.pricePerNight * (8 + (i * 3) % 25),
    }).save();

    savedHotels.push(newHotel);
  }

  console.log("Seeding sample bookings across Varanasi hotels…");
  const hotelA = savedHotels[0];
  const hotelB = savedHotels[1];
  const hotelC = savedHotels[4];

  const sampleBookings = [
    {
      hotelId: hotelA.id,
      userId: guest.id,
      firstName: "Guest",
      lastName: "Traveler",
      email: "guest@user.com",
      phone: "+91 98765 43210",
      adultCount: 2,
      childCount: 1,
      status: "confirmed",
      paymentStatus: "paid",
      paymentMethod: "upi",
      specialRequests: "Ganga river view upper floor room",
      checkIn: daysFromNow(7),
      checkOut: daysFromNow(10),
      createdAt: daysAgo(1),
      totalCost: hotelA.pricePerNight * 3,
      razorpayOrderId: "order_varanasi_upcoming_01",
      razorpayPaymentId: "pay_varanasi_upi_01",
    },
    {
      hotelId: hotelB.id,
      userId: guest.id,
      firstName: "Guest",
      lastName: "Traveler",
      email: "guest@user.com",
      phone: "+91 98765 43210",
      adultCount: 2,
      childCount: 0,
      status: "completed",
      paymentStatus: "paid",
      paymentMethod: "card",
      specialRequests: "Quiet garden facing suite",
      checkIn: daysAgo(15),
      checkOut: daysAgo(12),
      createdAt: daysAgo(30),
      totalCost: hotelB.pricePerNight * 3,
      razorpayOrderId: "order_varanasi_completed_02",
      razorpayPaymentId: "pay_varanasi_card_02",
    },
    {
      hotelId: hotelC.id,
      userId: admin.id,
      firstName: "Test",
      lastName: "Admin",
      email: "test@user.com",
      phone: "+91 98765 00001",
      adultCount: 1,
      childCount: 0,
      status: "completed",
      paymentStatus: "paid",
      paymentMethod: "upi",
      specialRequests: "Early morning boat transfer to Assi Ghat",
      checkIn: daysAgo(8),
      checkOut: daysAgo(6),
      createdAt: daysAgo(20),
      totalCost: hotelC.pricePerNight * 2,
      razorpayOrderId: "order_varanasi_admin_03",
      razorpayPaymentId: "pay_varanasi_upi_03",
    },
  ];

  for (const b of sampleBookings) {
    const bookingDoc = await new Booking({
      ...b,
      createdAt: b.createdAt,
      updatedAt: b.createdAt,
    }).save();

    if (b.status === "completed") {
      await new Review({
        userId: b.userId,
        hotelId: b.hotelId,
        bookingId: bookingDoc.id,
        rating: 5,
        comment: "Breathtaking stay in Varanasi! The river views, temple access, and hospitality were unforgettable.",
        categories: {
          cleanliness: 5,
          service: 5,
          location: 5,
          value: 5,
          amenities: 5,
        },
        isVerified: true,
        helpfulCount: 18,
      }).save();
    }
  }

  console.log("Seeding analytics snapshot for Varanasi…");
  await Analytics.create({
    date: new Date(),
    metrics: {
      totalBookings: sampleBookings.length,
      totalRevenue: sampleBookings.reduce((s, b) => s + b.totalCost, 0),
      totalUsers: 3,
      totalHotels: savedHotels.length,
      averageBookingValue: 8500,
      conversionRate: 74.2,
      cancellationRate: 4.8,
      averageRating: 4.8,
    },
    breakdown: {
      byStatus: {
        confirmed: 1,
        completed: 2,
        cancelled: 0,
        pending: 0,
        refunded: 0,
      },
      byPaymentStatus: {
        paid: 3,
        pending: 0,
        failed: 0,
        refunded: 0,
      },
      byDestination: [
        { city: "Varanasi", bookings: 3, revenue: sampleBookings.reduce((s, b) => s + b.totalCost, 0) },
      ],
      byHotelType: [
        { type: "Heritage", bookings: 1, revenue: hotelA.pricePerNight * 3 },
        { type: "Luxury", bookings: 1, revenue: hotelB.pricePerNight * 3 },
        { type: "Riverside", bookings: 1, revenue: hotelC.pricePerNight * 2 },
      ],
    },
  });

  console.log(`\n🎉 Seed Complete! Added ${savedHotels.length} authentic Varanasi hotels.`);
  console.log("  Admin Login: test@user.com / 12345678");
  console.log("  Owner Login: owner@hotel.com / 12345678");
  console.log("  Guest Login: guest@user.com / 12345678");

  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
